### ISSUE TITLE
Fork to Nissewaard

### ISSUE THREAD

**Issue by Martinvdm** [vloris/home-assistant#1]
Hi Floris,

As i do not want to fork your complete repo, i would like to let you know i used your code in a new project forked from yours with garbage collection of Nissewaard instead of Twentemilieu.

I added you as code owner.
https://github.com/Martinvdm/garbage-nissewaard-homeassistant

thanks!

Martin

**Comment by floriskruisselbrink** [comment]
You're welcome! Glad my work could be of some use :)
